# Generated by Django 5.0.6 on 2024-07-04 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('run_type', models.CharField(choices=[('Easy Run', 'Easy Run'), ('Long Run', 'Long Run'), ('Intervals', 'Intervals'), ('Tempo Run', 'Tempo Run')], default='Easy Run', max_length=20)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
