# Generated by Django 5.0.6 on 2024-08-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
