# Generated by Django 5.0.6 on 2024-09-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0003_run_hours_run_minutes_run_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
