# Generated by Django 5.0.6 on 2024-12-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0005_trainingblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingblock',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='trainingblock',
            old_name='start_date',
            new_name='startDate',
        ),
    ]
