# Generated by Django 5.0.6 on 2024-12-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0006_rename_end_date_trainingblock_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingblock',
            name='athlete',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainingblock',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
